version: '3.4'

services:
    db:
        image: mariadb:10.5.6
        environment:
            MYSQL_USER: r3
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: r3
        volumes:
            - r3_db_data:/var/lib/mysql
            - ./db-template.sql:/docker-entrypoint-initdb.d/db-template.sql
        ports:
            - "3306:3306"

    web:
        build: .
        depends_on:
          - db
        environment:
          DB_HOST: db
          DB_USER: r3
          DB_PASSWORD: password
          DB_NAME: r3
        ports:
          - "8080:80"
        volumes:
          - ./dist:/var/www/html/

    adminer:
      image: adminer
      ports:
        - 8088:8080

volumes:
    r3_db_data: ~
